# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pyinstaller publish

on:
  push:
    tags:
      - '*'

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          python-version: ["3.9","3.10"]
          os: [ubuntu-latest, macos-latest, windows-latest]

      steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install UPX compressor
        run: sudo apt-get install -y upx
      - name: Pyinstaller run
        run: |
          pyinstaller -n UninaDownloader main.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: UninaDownloader-${{ matrix.os}}-${{ matrix.python-version }}
          path: dist/UninaDownloader/
          if-no-files-found: error
          retention-days: 30

